import {
  pgTable, serial, integer, text, decimal, boolean, timestamp, date, time,
  uniqueIndex, index,
} from 'drizzle-orm/pg-core';
import { users, plants } from './schema.js';

export const plantProfiles = pgTable('plant_profiles', {
  id: serial('id').primaryKey(),
  plantId: integer('plant_id').notNull().references(() => plants.id, { onDelete: 'cascade' }),
  profileStatus: text('profile_status').notNull().default('draft'),
  productionCapacityM3PerHour: decimal('production_capacity_m3_per_hour', { precision: 8, scale: 2 }),
  maximumDailySupplyCapacityM3: decimal('maximum_daily_supply_capacity_m3', { precision: 10, scale: 2 }),
  numberOfTransitMixers: integer('number_of_transit_mixers'),
  numberOfPumps: integer('number_of_pumps'),
  inhouseConcretePumpAvailable: boolean('inhouse_concrete_pump_available'),
  externalPumpArrangementAvailable: boolean('external_pump_arrangement_available'),
  works24Hours: boolean('works_24_hours').notNull().default(false),
  workingHoursStart: time('working_hours_start'),
  workingHoursEnd: time('working_hours_end'),
  minimumOrderQuantityM3: decimal('minimum_order_quantity_m3', { precision: 8, scale: 2 }),
  laboratoryAvailable: boolean('laboratory_available'),
  laboratoryDetails: text('laboratory_details'),
  qualityEngineerAvailable: boolean('quality_engineer_available'),
  cubeTestingAvailable: boolean('cube_testing_available'),
  cubeTestingReportsAvailable: boolean('cube_testing_reports_available'),
  cubeTestingFrequency: text('cube_testing_frequency'),
  batchingCabinCameraAvailable: boolean('batching_cabin_camera_available'),
  batchReportAvailable: boolean('batch_report_available'),
  batchReportLinkedWithTm: boolean('batch_report_linked_with_tm'),
  challanAvailable: boolean('challan_available'),
  challanLinkedWithTm: boolean('challan_linked_with_tm'),
  dieselGeneratorAvailable: boolean('diesel_generator_available'),
  dieselGeneratorCapacityKva: decimal('diesel_generator_capacity_kva', { precision: 8, scale: 2 }),
  supportingPlantAvailable: boolean('supporting_plant_available'),
  supportingPlantName: text('supporting_plant_name'),
  supportingPlantDistanceKm: decimal('supporting_plant_distance_km', { precision: 8, scale: 2 }),
  breakdownBackupDescription: text('breakdown_backup_description'),
  plantMake: text('plant_make'),
  plantModel: text('plant_model'),
  numberOfSilos: integer('number_of_silos'),
  cementStorageCapacityMt: decimal('cement_storage_capacity_mt', { precision: 10, scale: 2 }),
  flyAshStorageCapacityMt: decimal('fly_ash_storage_capacity_mt', { precision: 10, scale: 2 }),
  aggregateStorageCapacityMt: decimal('aggregate_storage_capacity_mt', { precision: 10, scale: 2 }),
  weighbridgeAvailable: boolean('weighbridge_available'),
  gpsTrackingAvailable: boolean('gps_tracking_available'),
  plantManagerAvailable: boolean('plant_manager_available'),
  safetyOfficerAvailable: boolean('safety_officer_available'),
  emergencySupportAvailable: boolean('emergency_support_available'),
  cashPaymentAvailable: boolean('cash_payment_available'),
  smallQuantityCashPaymentAvailable: boolean('small_quantity_cash_payment_available'),
  creditPaymentAvailable: boolean('credit_payment_available'),
  creditDaysMin: integer('credit_days_min'),
  creditDaysMax: integer('credit_days_max'),
  advancePaymentRequired: boolean('advance_payment_required'),
  paymentTermsNotes: text('payment_terms_notes'),
  additionalInformation: text('additional_information'),
  completionPercentage: integer('completion_percentage').notNull().default(0),
  rejectionReason: text('rejection_reason'),
  submittedAt: timestamp('submitted_at'),
  reviewedAt: timestamp('reviewed_at'),
  reviewedBy: integer('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
  createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
  updatedBy: integer('updated_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  uniqueIndex('plant_profiles_plant_unique').on(t.plantId),
  index('plant_profiles_status_idx').on(t.profileStatus),
]);

export const plantCertificates = pgTable('plant_certificates', {
  id: serial('id').primaryKey(),
  plantId: integer('plant_id').notNull().references(() => plants.id, { onDelete: 'cascade' }),
  certificateType: text('certificate_type').notNull(),
  certificateName: text('certificate_name').notNull(),
  certificateStatus: text('certificate_status').notNull().default('available'),
  certificateNumber: text('certificate_number'),
  issuingAuthority: text('issuing_authority'),
  issueDate: date('issue_date'),
  expiryDate: date('expiry_date'),
  documentUrl: text('document_url'),
  verificationStatus: text('verification_status').notNull().default('unverified'),
  verificationMethod: text('verification_method').notNull().default('not_verified'),
  isVisibleToCustomer: boolean('is_visible_to_customer').notNull().default(false),
  ownerNotes: text('owner_notes'),
  verifiedBy: integer('verified_by').references(() => users.id, { onDelete: 'set null' }),
  verifiedAt: timestamp('verified_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  index('plant_certificates_plant_idx').on(t.plantId),
  index('plant_certificates_verification_idx').on(t.verificationStatus),
  index('plant_certificates_expiry_idx').on(t.expiryDate),
]);

export const plantPromotions = pgTable('plant_promotions', {
  id: serial('id').primaryKey(),
  plantId: integer('plant_id').notNull().references(() => plants.id, { onDelete: 'cascade' }),
  packageType: text('package_type').notNull().default('standard'),
  promotionRadiusKm: decimal('promotion_radius_km', { precision: 8, scale: 2 }).notNull().default('20'),
  priorityRank: integer('priority_rank').notNull().default(1),
  bannerTitle: text('banner_title').notNull().default('Featured RMC Plant'),
  bannerSubtitle: text('banner_subtitle'),
  showGlowingEffect: boolean('show_glowing_effect').notNull().default(true),
  paymentStatus: text('payment_status').notNull().default('pending'),
  startAt: timestamp('start_at').notNull(),
  endAt: timestamp('end_at').notNull(),
  isActive: boolean('is_active').notNull().default(false),
  amountPaid: decimal('amount_paid', { precision: 12, scale: 2 }),
  paymentReference: text('payment_reference'),
  internalNotes: text('internal_notes'),
  createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
  updatedBy: integer('updated_by').references(() => users.id, { onDelete: 'set null' }),
  approvedBy: integer('approved_by').references(() => users.id, { onDelete: 'set null' }),
  approvedAt: timestamp('approved_at'),
  suspendedAt: timestamp('suspended_at'),
  suspensionReason: text('suspension_reason'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  index('plant_promotions_plant_idx').on(t.plantId),
  index('plant_promotions_active_idx').on(t.isActive),
  index('plant_promotions_start_idx').on(t.startAt),
  index('plant_promotions_end_idx').on(t.endAt),
]);
