export function accountDeletionPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Concrete King – Account and Data Deletion</title>
<meta name="description" content="Request deletion of your Concrete King account and associated personal data.">
<style>
:root{color-scheme:light;--ink:#172033;--muted:#526078;--brand:#08785f;--line:#dce4e8;--bg:#f4f8f7;--danger:#b42318}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,-apple-system,Segoe UI,sans-serif}.wrap{width:min(880px,calc(100% - 32px));margin:auto;padding:28px 0 64px}.brand{font-weight:900;letter-spacing:.04em;color:var(--brand)}main{background:#fff;border:1px solid var(--line);border-radius:18px;padding:clamp(22px,5vw,46px);box-shadow:0 18px 50px rgba(23,32,51,.08)}h1{font-size:clamp(28px,5vw,42px);line-height:1.14;margin:8px 0 16px}h2{font-size:21px;margin:32px 0 10px}.identity{background:#eef8f5;border-left:4px solid var(--brand);padding:16px 18px;border-radius:8px}.identity strong{display:block}.muted{color:var(--muted)}label{display:block;font-weight:700;margin:16px 0 6px}input,textarea{width:100%;font:inherit;padding:12px;border:1px solid #aebbc5;border-radius:8px}textarea{min-height:100px;resize:vertical}.check{display:flex;gap:10px;align-items:flex-start;font-weight:600}.check input{width:20px;height:20px;margin-top:3px}button{width:100%;min-height:50px;border:0;border-radius:9px;background:var(--brand);color:#fff;font-weight:900;font-size:15px;margin-top:20px;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.notice{margin-top:18px;padding:15px;border-radius:8px;display:none}.ok{display:block;background:#eaf8ef;color:#176b36}.error{display:block;background:#fff0ee;color:var(--danger)}a{color:var(--brand)}footer{text-align:center;color:var(--muted);margin-top:20px;font-size:14px}@media(max-width:520px){.wrap{width:min(100% - 20px,880px);padding-top:10px}main{border-radius:12px;padding:20px}}
</style></head><body><div class="wrap"><main>
<div class="brand">CONCRETE KING · Powered by TrackMyRMC</div>
<h1>Concrete King – Account and Data Deletion</h1>
<div class="identity"><strong>Google Play application:</strong>Concrete King | Ready-Mix Concrete Tracking &amp; RMC Plant Discovery<br><br><strong>Package name:</strong>com.trackmyrmc.concreteking<br><br><strong>Powered by TrackMyRMC</strong></div>
<p>Registered users can use this official page to request deletion of their Concrete King account and associated personal data without signing in. We may contact you to verify that you own the account.</p>
<h2>What will be deleted</h2><p class="muted">Eligible profile information, registered mobile number and email address, saved delivery addresses, profile image, authentication information, active sessions, refresh tokens, device tokens, non-essential location information, and other account-linked personal information will be deleted or anonymized.</p>
<h2>Records we may retain</h2><p class="muted">Orders, invoices, delivery challans, payments, tax records, security logs and fraud-prevention or regulatory records may be retained for the period required by applicable law. Unnecessary personal information is removed from retained business records. Access is restricted and retained data is deleted or anonymized when the applicable legal retention period ends.</p>
<h2>Request account deletion</h2>
<form id="deletion-form" novalidate>
<label for="fullName">Full name</label><input id="fullName" name="fullName" maxlength="120" autocomplete="name" required>
<label for="mobile">Registered mobile number</label><input id="mobile" name="mobile" maxlength="30" inputmode="tel" autocomplete="tel" required>
<label for="email">Registered email address <span class="muted">(optional)</span></label><input id="email" name="email" maxlength="254" type="email" autocomplete="email">
<label for="reason">Reason for deletion <span class="muted">(optional)</span></label><textarea id="reason" name="reason" maxlength="1000"></textarea>
<label class="check"><input id="confirmed" name="confirmed" type="checkbox" required><span>I confirm that I want to delete my Concrete King account and associated personal data.</span></label>
<button type="submit">REQUEST ACCOUNT DELETION</button><div id="notice" class="notice" role="status" aria-live="polite"></div>
</form>
<p class="muted">Need help? Email <a href="mailto:support@goldetech.com">support@goldetech.com</a>. Read our <a href="/privacy">Privacy Policy</a>.</p>
</main><footer>Concrete King · com.trackmyrmc.concreteking · Powered by TrackMyRMC</footer></div>
<script>document.getElementById('deletion-form').addEventListener('submit',async function(e){e.preventDefault();const f=e.currentTarget,n=document.getElementById('notice'),b=f.querySelector('button');n.className='notice';n.textContent='';if(!f.reportValidity())return;b.disabled=true;try{const r=await fetch('/api/account-deletion-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:f.fullName.value,mobile:f.mobile.value,email:f.email.value,reason:f.reason.value,confirmed:f.confirmed.checked})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to register the request.');n.className='notice ok';n.textContent='Deletion request received. Your request has been registered successfully. We may contact you to verify account ownership. Eligible account and personal data will be deleted within 7 working days. Records required for legal, tax, transaction, fraud-prevention or regulatory purposes may be retained for the legally required period.';f.reset()}catch(x){n.className='notice error';n.textContent=x.message||'Unable to register the request.'}finally{b.disabled=false}});</script>
</body></html>`;
}
