// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ck-landing/Landing.tsx": () => import("../components/mockups/ck-landing/Landing.tsx"),
  "./components/mockups/concrete-king-deck/BlueprintDeck.tsx": () => import("../components/mockups/concrete-king-deck/BlueprintDeck.tsx"),
  "./components/mockups/concrete-king-deck/EditorialDeck.tsx": () => import("../components/mockups/concrete-king-deck/EditorialDeck.tsx"),
  "./components/mockups/concrete-king-deck/EtherealGlassDeck.tsx": () => import("../components/mockups/concrete-king-deck/EtherealGlassDeck.tsx"),
  "./components/mockups/concrete-king-deck/GalleryEditorialDeck.tsx": () => import("../components/mockups/concrete-king-deck/GalleryEditorialDeck.tsx"),
  "./components/mockups/concrete-king-deck/LandingDeck.tsx": () => import("../components/mockups/concrete-king-deck/LandingDeck.tsx"),
  "./components/mockups/concrete-king-deck/MagazineEditorialDeck.tsx": () => import("../components/mockups/concrete-king-deck/MagazineEditorialDeck.tsx"),
  "./components/mockups/concrete-king-deck/SiteBrutalistDeck.tsx": () => import("../components/mockups/concrete-king-deck/SiteBrutalistDeck.tsx"),
  "./components/mockups/concrete-king-deck/SoftSereneDeck.tsx": () => import("../components/mockups/concrete-king-deck/SoftSereneDeck.tsx"),
  "./components/mockups/redesign/AuroraGlass.tsx": () => import("../components/mockups/redesign/AuroraGlass.tsx"),
  "./components/mockups/redesign/DaylightGlass.tsx": () => import("../components/mockups/redesign/DaylightGlass.tsx"),
  "./components/mockups/redesign/DaylightOps.tsx": () => import("../components/mockups/redesign/DaylightOps.tsx"),
  "./components/mockups/redesign/IndustrialSteel.tsx": () => import("../components/mockups/redesign/IndustrialSteel.tsx"),
  "./components/mockups/rmc-dashboard/CommandCenter.tsx": () => import("../components/mockups/rmc-dashboard/CommandCenter.tsx"),
  "./components/mockups/rmc-dashboard/ExceptionFirst.tsx": () => import("../components/mockups/rmc-dashboard/ExceptionFirst.tsx"),
  "./components/mockups/rmc-dashboard/ShiftHandover.tsx": () => import("../components/mockups/rmc-dashboard/ShiftHandover.tsx"),
  "./components/mockups/superadmin/PlatformControlCenter.tsx": () => import("../components/mockups/superadmin/PlatformControlCenter.tsx")
};
